### ISSUE TITLE
vertical whitespace between forms

### ISSUE THREAD

**Issue by eigenhombre** [candid82/cljf#1]
Would you be open to standardizing vertical whitespace between forms?  My Python (`black`), Go (`gofmt`), C (`clang-format`) and I think JavaScript (`prettier`) formatters all support this.

The simplest possible helpful rule would be to change all expressions with multiple blank lines between them to having a single blank line (e.g.,

```
(def a 3)


(def b 4)
```
becomes
```
(def a 3)

(def b 4)
```

but 
```
(def a 3)
(def b 4)
```

stays unchanged.  This is how `clang-format` seems to work.

`Black` is more aggressive in that all functions must have two blank lines between them, consistent w/ Python's PEP-8 standard, but that is not so idiomatic in Clojure code, I don't think.

If you're open to it, and don't want to do it yourself, I might take a crack at it.  Thanks for making this tool.

**Comment by candid82** [comment]
@eigenhombre I think this makes sense, thank you for the suggestion. It's implemented in https://github.com/candid82/cljf/commit/41ceabf73b60c34984febe930c6ca16969aa364a I put it behind `SINGLE_BLANK_LINE_BETWEEN_FORMS` define, so that this behavior can be easily turned off (but it's on by default).

**Comment by eigenhombre** [comment]
Awesome, thank you!
